# Generated by Django 2.2.8 on 2020-08-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200624_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
    ]
