# Generated by Django 2.2.8 on 2020-06-11 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_choice',
            field=models.CharField(blank=True, choices=[('S', 'Stripe'), ('B', 'Bank Transfer')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, choices=[('N', 'No Designation'), ('A', 'morning'), ('B', '0pm-2pm'), ('C', '2pm-4pm'), ('D', '4pm-6pm'), ('E', '6pm-8pm')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
