# Generated by Django 2.2.8 on 2020-06-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200611_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_choice',
            new_name='payment_option',
        ),
    ]
