# Generated by Django 2.2.8 on 2020-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200612_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='apartment_address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(default='CA', max_length=100),
        ),
    ]
