# Generated by Django 2.2.8 on 2020-07-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_item_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('L', 'PC'), ('P', 'Parts'), ('G', 'Green'), ('F', 'Furniture')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='original_images', verbose_name='メイン画像(option)'),
        ),
    ]
