# Generated by Django 2.2.8 on 2020-07-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200728_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipped',
            new_name='dispatched',
        ),
    ]
