# Generated by Django 2.2.8 on 2020-08-12 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0030_item_fav_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fav_users',
            field=models.ManyToManyField(blank=True, related_name='fav_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Store Title', max_length=255, verbose_name='ショップ名')),
                ('free_shippment_line', models.IntegerField(blank=True, null=True, verbose_name='送料無料最低価格')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='送料')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='Site')),
            ],
        ),
    ]
