# Generated by Django 2.2.8 on 2020-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200812_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='order_history_paginate_by',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='order_list_paginate_by',
            field=models.IntegerField(default=5),
        ),
    ]
