# Generated by Django 2.2.8 on 2020-08-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200820_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Category', verbose_name='カテゴリー(option)'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='order_history_paginate_by',
            field=models.IntegerField(default=5, verbose_name='購入履歴ページネーション'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='order_list_paginate_by',
            field=models.IntegerField(default=5, verbose_name='オーダーリストページネーション'),
        ),
    ]
