# Generated by Django 2.2.8 on 2020-08-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200820_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'オーダー'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'カート内商品'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Stripe'},
        ),
        migrations.AlterModelOptions(
            name='siteinfo',
            options={'verbose_name_plural': 'サイト設定'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1, verbose_name='メニュー順番'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='商品説明'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='セール価格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='非公開'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='メイン画像'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=2, null=True, verbose_name='レーベル'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='在庫数'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='order_history_paginate_by',
            field=models.IntegerField(default=5, verbose_name='購入履歴1ページ表示数'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='order_list_paginate_by',
            field=models.IntegerField(default=5, verbose_name='注文管理1ページ表示数'),
        ),
    ]
