# Generated by Django 2.2.8 on 2020-08-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'お問い合わせ'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'カート内全商品/注文済注文'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'カート内各商品'},
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='在庫数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_option', to='core.Item')),
            ],
            options={
                'verbose_name_plural': '商品サイズ',
                'unique_together': {('item', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='在庫数')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_option', to='core.Item')),
            ],
            options={
                'verbose_name_plural': '商品カラー',
                'unique_together': {('item', 'value')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ColorOption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SizeOption'),
        ),
    ]
