# Generated by Django 2.2.8 on 2021-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210227_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='item_main_image/', verbose_name='メイン画像'),
        ),
    ]
