# Generated by Django 2.2.8 on 2021-03-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210301_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='トップページ厳選'),
        ),
        migrations.AlterField(
            model_name='item',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='非公開にする'),
        ),
        migrations.AlterField(
            model_name='item',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='トップページおすすめ'),
        ),
    ]
