# Generated by Django 2.2.8 on 2021-03-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20210307_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PhotoCategory',
        ),
    ]
