# Generated by Django 2.2.8 on 2021-03-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20210316_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='PhotoTag',
        ),
    ]
