# Generated by Django 2.2.8 on 2021-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='blog-main-image/', verbose_name='メイン画像(option)'),
        ),
    ]
