# Generated by Django 2.2.8 on 2021-03-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210316_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='whatsnew',
            field=models.BooleanField(default=False, verbose_name="What's New"),
        ),
    ]
